# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inspection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField()),
                ('purposeOfInspection', models.CharField(choices=[('C', 'Compliance'), ('R', 'Routine'), ('F', 'Field Investigation'), ('V', 'Visit'), ('O', 'Other')], max_length=1)),
                ('employeeUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='inspectionItemDetail',
            fields=[
                ('subhead', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='inspectionItemStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complianceStatus', models.IntegerField(choices=[('1', 'not in compliance'), ('2', 'in compliance'), ('3', 'not observed'), ('4', 'not applicable '), ('5', 'corrected on site')], max_length=1)),
                ('inspectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvi.inspection')),
                ('itemDetailsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvi.inspectionItemDetail')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='priorityLevel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('levelPoints', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('owner', models.CharField(max_length=30)),
                ('licensePermit', models.IntegerField()),
                ('restaurantType', models.CharField(choices=[('B', 'Buffet'), ('F', 'Fast Food'), ('S', 'Small Shop')], max_length=1)),
                ('riskType', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='inspectionitemdetail',
            name='priorityLevelId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvi.priorityLevel'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='restaurantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvi.restaurant'),
        ),
    ]
