# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitemstatus',
            name='complianceStatus',
            field=models.IntegerField(choices=[('1', 'not in compliance'), ('2', 'in compliance'), ('3', 'not observed'), ('4', 'not applicable '), ('5', 'corrected on site')]),
        ),
    ]
