# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compliance_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('spelled_out_compstatus', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='inspection_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subhead', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='inspection_item_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='priority_level',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_points', models.IntegerField()),
                ('inspection_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.inspection_item')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('purpose_of_inspection', models.IntegerField()),
                ('COS_violation_count', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.employee')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('owner', models.TextField(max_length=100)),
                ('license_permit', models.IntegerField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='restaurant_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.restaurant')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.restaurant'),
        ),
        migrations.AddField(
            model_name='inspection_item_status',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.report'),
        ),
        migrations.AddField(
            model_name='inspection_item',
            name='inspection_item_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.inspection_item_status'),
        ),
        migrations.AddField(
            model_name='compliance_status',
            name='inspection_item_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_venue_inspection.inspection_item_status'),
        ),
    ]
